Seminar_algebra/Controllers/ZaposleniksController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Seminar_algebra.Models;

namespace Seminar_algebra.Controllers
{
    [Authorize]
    public class ZaposleniksController : Controller
    {
        private bazaDbContext db = new bazaDbContext();

        // GET: Zaposleniks
        public ActionResult Index()
        {
            return View(db._dboZp.ToList());
        }

        // GET: Zaposleniks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenik zaposlenik = db._dboZp.Find(id);
            if (zaposlenik == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenik);
        }

        
        [Authorize (Users = "Admin")]
        // GET: Zaposleniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenik zaposlenik = db._dboZp.Find(id);
            if (zaposlenik == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenik);
        }

        // POST: Zaposleniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdZaposlenik,Ime,Prezime,KorisnickoIme,Lozinka")] Zaposlenik zaposlenik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zaposlenik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(zaposlenik);
        }

        // GET: Zaposleniks/Delete/5
        [Authorize(Users = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenik zaposlenik = db._dboZp.Find(id);
            if (zaposlenik == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenik);
        }

        // POST: Zaposleniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zaposlenik zaposlenik = db._dboZp.Find(id);
            db._dboZp.Remove(zaposlenik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Seminar_algebra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Benic Seminar</title>
    
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
 
  
   

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Početna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Seminari", "Popis", "Seminari", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Zaposlenici", "Index", "Zaposleniks", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse navbar-right ">
            
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Popis upisanih", "upisi", "Seminari",null, new { @class = "nav-link" })</li>



                        <li>@Html.ActionLink("Novi Zaposlenik", "Register", "Home", null, new { @class = "nav-link" })</li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-center text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                
                                @Html.ActionLink("Odjava", "Logout", "Home", new { @class = "nav-link text-center text-uppercase" }, null)
                            </div>
                        </li>

                    }
                    else
                    {



                        <li>@Html.ActionLink("Prijava", "Login", "Home", null, new { @class = "nav-link float-left" })</li>



                    }
                </ul>
            </div>

        </div>


    </div>


    <div class="container text-center" ; style=" width:80% ; margin: auto;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ante Benic Seminar</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>